---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-sync
  namespace: monitoring
spec:
  interval: 10m0s
  path: ./applications
  prune: true
  sourceRef:
    kind: GitRepository
    name: monitoring-flux-infra
    namespace: flux-system
