---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: base-values
    files:
      - kube-prometheus-stack-values.yaml=kube-prometheus-stack/values.yaml
      - loki-stack-values.yaml=loki-stack/values.yaml
  - name: base-kube-state-metrics
    files:
      - kube-state-metrics.yaml=kube-prometheus-stack/metrics.yaml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
configurations:
  - kustomize.yaml
generatorOptions:
  disableNameSuffixHash: true
namespace: monitoring
resources:
  - kube-prometheus-stack
  - loki-stack
  - sources.yaml
