apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
configMapGenerator:
  - name: base-values
    files:
      - kube-prometheus-stack-values.yaml=kube-prometheus-stack/values.yaml
  - name: base-config
    files:
      - kube-state-metrics-config.yaml=kube-prometheus-stack/metrics.yaml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
configurations:
  - kustomize.yaml
generatorOptions:
  disableNameSuffixHash: true
resources:
  - kube-prometheus-stack
  - sources.yaml
