---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: feature/add_example_application
  url: https://github.com/ehaldane-digicatapult/monitoring-flux-infra.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./examples/kind/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
