---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: monitoring-flux-infra
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/ehaldane-digicatapult/monitoring-flux-infra.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-sync
  namespace: monitoring
spec:
  interval: 10m0s
  path: ./applications
  prune: true
  sourceRef:
    kind: GitRepository
    name: monitoring-flux-infra
    namespace: flux-system
