---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: configuration-sync
  namespace: monitoring
configMapGenerator:
  - name: base-dashboards
    files:
      - dashboards/cluster.json
      - dashboards/controlplane.json
      - dashboards/logs.json
    options:
      labels:
        app.kubernetes.io/component: monitoring
        app.kubernetes.io/part-of: flux
        grafana_dashboard: "1"
        kustomize.toolkit.fluxcd.io/substitute: disabled
generatorOptions:
  disableNameSuffixHash: true
resources:
  - monitors/podmonitor.yaml
