---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: environment-sync
  namespace: monitoring
configMapGenerator:
  - name: env-values
    files:
      - kube-prometheus-stack-values.yaml=substitutions/kube-prometheus-stack-values.yaml
      - loki-stack-values.yaml=substitutions/loki-stack-values.yaml
configurations:
  - kustomize.yaml
generatorOptions:
  disableNameSuffixHash: true
resources:
  - applications.yaml
  - infrastructure.yaml
